---
name: Build all borealos artifacts
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 10 * * 0'  # 10:05am UTC every Sunday
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-container:
    name: Build borealos container images
    uses: ./.github/workflows/build-container.yml
    secrets: inherit
    with:
      images: '["borealos", "borealos-nvidia", "borealos-nvidia-open"]'
      source_tag: stable

  build-iso:
    name: Build borealos ISO installer images
    uses: ./.github/workflows/build-iso.yml
    needs:
      - build-container
    with:
      images: '["borealos", "borealos-nvidia", "borealos-nvidia-open"]'
      tag: stable
