name: Build borealos installer images
on:
  workflow_dispatch:
    inputs:
      images:
        description: Image descriptors of the installers to build
        type: choice
        options:
          - '["borealos"]'
          - '["borealos-nvidia-open"]'
          - '["borealos", "borealos-nvidia-open"]'
        default: '["borealos", "borealos-nvidia-open"]'
      tag:
        description: Image tag to build an installer for
        type: choice
        options:
          - stable
        default: stable
  workflow_call:
    inputs:
      images:
        description: image descriptors of the installers to build
        type: string
        default: '["borealos", "borealos-nvidia-open"]'
      tag:
        description: Image tag to build an installer for
        type: string
        default: stable

env:
  IMAGE_REGISTRY: ghcr.io/hal7df

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}.iso
  cancel-in-progress: true

jobs:
  build-iso:
    name: Build ISO installers for ${{ matrix.image }}:${{ inputs.tag }}
    outputs:
      url: ${{ steps.upload.outputs.artifact-url }}
    runs-on: ubuntu-26.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson (inputs.images) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@695eb75bc387dbcd9685a8e72d23439d8686cba6 #v10

      - name: Install Just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 #v4.0.0

      - name: Lint Justfile
        shell: bash
        run: just lint

      - name: Build ISO
        id: iso
        shell: bash
        run: |
          JUST="$(command -v just)"
          sudo --preserve-env=PATH "${JUST}" build-iso ${{ matrix.image }} "podman-push-debug" 1 1
          ls -l build/output/${{ matrix.image }}-${{ inputs.tag }}.iso
          awk '{printf "sha256=%s\n", $1}' build/output/${{ matrix.image }}-podman-push-debug.iso.sha256 >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT

      - name: Upload ISO as job artifact
        id: upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: ${{ matrix.image }}-${{ inputs.tag }}.iso
          path: build/output/${{ matrix.image }}-${{ inputs.tag }}.iso*
          if-no-files-found: error
          retention-days: 90
          compression-level: 0
          overwrite: true
